/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.ex_51;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author jeffe
 */
public class NewJFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    DecimalFormat df = new DecimalFormat("###,##0.00");

    StringBuilder sb = new StringBuilder();

    double resultadoCorrente;
    double disjuntor;

    public void CorrenteAmperes() {

        try {
            double watts = Double.parseDouble(txtWatts.getText());

            if (rb110v.isSelected()) {
                resultadoCorrente = watts / 110;
            } else {
                resultadoCorrente = watts / 220;
            }

            txtCorrenteAmperes.setText(df.format(resultadoCorrente));

        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ERRO: Você digitou algo indevido.");
        }
    }

    public void LimparEscolha() {
        cbDisjuntor.setSelected(false);
        cbBitola.setSelected(false);
    }

    public void VerificarEscolha() {

        sb.setLength(0);

        disjuntor = resultadoCorrente * 1.25;

        if (cbDisjuntor.isSelected()) {
            sb.append("Valor para o disjuntor: " + df.format(disjuntor) + "\n-----------------------------\n");
        }
        if (cbBitola.isSelected()) {
            if (disjuntor <= 12) {
                sb.append("Disjuntor recomendado: 12\n-----------------------------\nBitola do fio recomendado: 1,0mm");
            } else if (disjuntor <= 15) {
                sb.append("Disjuntor recomendado: 15\n-----------------------------\nBitola do fio recomendado: 1,5mm");
            } else if (disjuntor <= 21) {
                sb.append("Disjuntor recomendado: 21\n-----------------------------\nBitola do fio recomendado: 2,5mm");
            } else if (disjuntor <= 28) {
                sb.append("Disjuntor recomendado: 28\n-----------------------------\nBitola do fio recomendado: 4mm");
            } else if (disjuntor <= 36) {
                sb.append("Disjuntor recomendado: 36\n-----------------------------\nBitola do fio recomendado: 6mm");
            } else if (disjuntor <= 50) {
                sb.append("Disjuntor recomendado: 50\n-----------------------------\nBitola do fio recomendado: 10mm");
            } else {
                sb.append("Disjuntor recomendado: 68\n-----------------------------\nBitola do fio recomendado: 16mm");
            }
        }

        txaSaida.setText(sb.toString());

        LimparEscolha();

    }

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtWatts = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rb110v = new javax.swing.JRadioButton();
        rb220v = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtCorrenteAmperes = new javax.swing.JTextField();
        cbDisjuntor = new javax.swing.JCheckBox();
        cbBitola = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaSaida = new javax.swing.JTextArea();
        btnSelecionar = new javax.swing.JButton();
        btnEscolher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Digite o valor da potencia:");

        txtWatts.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Escolha uma voltagem:");

        buttonGroup1.add(rb110v);
        rb110v.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rb110v.setText("110v");

        buttonGroup1.add(rb220v);
        rb220v.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rb220v.setText("220v");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Corrente em amperes:");

        txtCorrenteAmperes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCorrenteAmperes.setEnabled(false);

        cbDisjuntor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbDisjuntor.setText("Sugestão valor para um disjuntor");

        cbBitola.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbBitola.setText("Sugestão de bitola para os fios");

        txaSaida.setColumns(20);
        txaSaida.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txaSaida.setRows(5);
        txaSaida.setEnabled(false);
        jScrollPane1.setViewportView(txaSaida);

        btnSelecionar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(this::btnSelecionarActionPerformed);

        btnEscolher.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEscolher.setText("Escolher");
        btnEscolher.addActionListener(this::btnEscolherActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbDisjuntor)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCorrenteAmperes, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb110v)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb220v)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEscolher))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtWatts, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSelecionar)
                            .addComponent(cbBitola))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtWatts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rb110v)
                    .addComponent(rb220v)
                    .addComponent(btnEscolher))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCorrenteAmperes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbDisjuntor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbBitola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSelecionar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolherActionPerformed
        // TODO add your handling code here:
        CorrenteAmperes();
    }//GEN-LAST:event_btnEscolherActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        // TODO add your handling code here:
        VerificarEscolha();
    }//GEN-LAST:event_btnSelecionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try{
            com.formdev.flatlaf.intellijthemes.FlatMaterialDesignDarkIJTheme.setup();
        }catch(Exception e){
            System.out.println("Erro ao carregar o Look and Feel.");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscolher;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbBitola;
    private javax.swing.JCheckBox cbDisjuntor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb110v;
    private javax.swing.JRadioButton rb220v;
    private javax.swing.JTextArea txaSaida;
    private javax.swing.JTextField txtCorrenteAmperes;
    private javax.swing.JTextField txtWatts;
    // End of variables declaration//GEN-END:variables
}
